load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
  name = "com_google_absl_oss_federation",
  urls = ["https://github.com/abseil/federation-head/archive/de0427776d7a783d8011795282fda13976e53682.zip"],  # 2021-05-31T08:17:51Z
  strip_prefix = "federation-head-de0427776d7a783d8011795282fda13976e53682",
  sha256 = "654be6c8db9edaddd058e7ff66589af20d7d6d49407244f0600f6c635b2c9440",
)

load("@com_google_absl_oss_federation//:federation_deps.bzl", "federation_deps")

federation_deps()

